[package]
name = "sqlc-rust-postgres"
version = "0.1.0"
edition = "2021"

[dependencies]
convert_case = { version = "0.7.1", default-features = false }
prost = { version = "0.13.4" }

prettyplease = { version = "0.2" }
proc-macro2 = { version = "1.0.93" }
quote = { version = "1.0" }
syn = { version = "2", default-features = false, features = [
    "full",
    "parsing",
] }

[dev-dependencies]
tokio-postgres = { version = "0.7.13" }
postgres-types = { version = "0.2.9", features = ["derive"] }

[build-dependencies]
prost-build = "0.13.4"
