name: Rust CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - "**.rs"
      - '**Cargo.toml'
      - '**Cargo.lock'
      - "rust-toolchain.toml"
      - "rustfmt.toml"
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  RUST_LOG: info
  RUST_BACKTRACE: 1
  RUSTFLAGS: --deny warnings

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
      - name: Install Rust
        uses: moonrepo/setup-rust@v1
        with:
          components: rustfmt
          cache-base: main
      - name: Run format
        run: |
          cargo fmt --all --check
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
      - name: Install Rust
        uses: moonrepo/setup-rust@v1
        with:
          components: clippy
          cache-base: main
      - name: Setup Protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "3.21.12"
      - name: Run lint
        run: |
          cargo clippy --all-targets --all-features
